# Generated by Django 3.2.19 on 2023-06-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Количество товара'),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Общая цена товара'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
