# Generated by Django 3.2.19 on 2023-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230614_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtype',
            options={'verbose_name': 'Тип карты', 'verbose_name_plural': 'Типы карт'},
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(null=True, upload_to='genre_images/', verbose_name='Изображение'),
        ),
    ]
