# Generated by Django 3.2.19 on 2023-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230614_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Рейтинг'),
        ),
    ]
