# Generated by Django 3.2.19 on 2023-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Оценка'),
        ),
    ]
