# Generated by Django 3.2.19 on 2023-06-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_text',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
    ]
